name: Build Packages
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/**'
jobs:
  checks:
    name: Build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/gh-setup
      - name: Build
        run: yarn build
      - name: Types
        run: yarn types:react
      - name: Test
        run: yarn test
