name: Checks Storefront
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/storefront/**'
  push:
    paths:
      - 'apps/storefront/**'
jobs:
  checks:
    name: Builds, lints and tests code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Use node 20 and yarn cache
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build packages
        run: yarn build
      - name: Build storefront
        run: yarn build:storefront
      - name: Types
        run: yarn types:storefront
      - name: Lint Code
        run: yarn lint ./apps/storefront
      - name: Lint CSS
        run: yarn lint-style ./apps/storefront/**/*.css
      - name: Test
        run: yarn test
